version: 2
updates:
- package-ecosystem: maven
  directory: "/betterrandom"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.wvengen:proguard-maven-plugin
    versions:
    - "< 2.3.1"
    - ">= 2.3.0"
  - dependency-name: org.javassist:javassist
    versions:
    - "< 3.23.1"
    - ">= 3.23.0-GA.a"
  - dependency-name: org.javassist:javassist
    versions:
    - "< 3.23.2"
    - ">= 3.23.1-GA.a"
  - dependency-name: org.javassist:javassist
    versions:
    - "< 3.24.1"
    - ">= 3.24.0-GA.a"
  - dependency-name: org.javassist:javassist
    versions:
    - "< 3.24.2"
    - ">= 3.24.1-GA.a"
  - dependency-name: org.javassist:javassist
    versions:
    - ">= 3.25.0-GA.a"
    - "< 3.25.1"
  - dependency-name: org.mockito:mockito-core
    versions:
    - ">= 3.4.2.a"
    - "< 3.4.3"
  - dependency-name: org.testng:testng
    versions:
    - ">= 7.1.0.a"
    - "< 7.1.1"
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/FifoFiller"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
