# http://www.appveyor.com/docs/appveyor-yml
init:
  - rmdir c:\cygwin /s /q
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  matrix:
   - OP: unit-tests
     RUNNER: MinGW\msys\1.0
   - OP: unit-tests
     RUNNER: cygwin64
   - OP: benchmark
     RUNNER: MinGW\msys\1.0
   - OP: benchmark
     RUNNER: cygwin64
  access_token:
    secure: UrMOuu5SzFyDvmnIwDu4EJol6YwyLJJ3yAAvA8URK7x8cmssL4106Wr8MmS01GGL
  random_dot_org_key:
    secure: SdVpsz4/hDKlxV/jEehj9kEUmbIrrq5yvDOWYrHyxN+WE1z8CNeeTnv8BuQ6XsnN
  APPVEYOR_RDP_PASSWORD:
    secure: prROYXFdZ1WD7poOqYxXuRIF6KkKWjAWAWZX5PaHABM=
install:
  # Log versions for debugging
  - java -version
  - mvn --version
build_script:
  # shell scripts both build and test, so all we need to do here is set the character encoding
  - chcp 65001
test_script:
  - c:\%RUNNER%\bin\sh ./%OP%.sh
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
matrix:
  fast_finish: true
  allow_failures:
    - ALLOW_FAILURE: true
